### ISSUE TITLE
Screen Design

### ISSUE THREAD

**Issue by matanpugach** [TechnionYP5779/team1-Social-Geha#11]
Screen Design for the App

**Comment by saifun** [comment]
Done.
We created a brief sketch for the screens of the first basic version.
Any other details will be added later on.
The final version could be found [here ](https://drive.google.com/file/d/10Ej8l3hJ6dul3LBYLeXN6G04HKOUZUqa/view?usp=sharing)and also in the report.
The design was sent to the client for feedback.
