### ISSUE TITLE
Writing the Report

### ISSUE THREAD

**Issue by matanpugach** [TechnionYP5779/team1-Social-Geha#13]

**Comment by matanpugach** [comment]
#3 #4 #5 #6 #7

**Comment by saifun** [comment]
Please open a Google Docs document, and share it with us so we can comment and add things.

**Comment by saifun** [comment]
[This ](https://docs.google.com/document/d/15izKhZkrHcyp8mTVWHNzbp4o2QUEUGo3kCcO6lFFh0Y/edit?usp=sharing)is a link to a shared Google Doc for the report. 
Each of us can fill his own parts. For now it contains the template.

**Comment by ShaiZeevi** [comment]
The only remaining chapter is the one concerning the anonymity algorithm. I feel like we can submit the report without it though (or as an appendix).

**Comment by saifun** [comment]
Do you think this could be done for this iteration? I agree that it's not must, but could be very nice. Maybe just add a brief explanation if you don't want to deep into details yet.
@yoavz1997

**Comment by saifun** [comment]
I read the report and added some things. It's written very nicely - good job, @ShaiZeevi!
There is a bit of an issue with the table of contents (and with the numbering of the sections).
After fixing this - LGTM 🥇

**Comment by ShaiZeevi** [comment]
I fixed the table of contents, indentations, numberings, etc. Would you like to take a 2nd look?
@matanpugach @saifun

**Comment by saifun** [comment]
Nice! I changed some inconsistent fonts and now it looks great.
