### ISSUE TITLE
Report Modifications

### ISSUE THREAD

**Issue by yoavz1997** [TechnionYP5779/team1-Social-Geha#17]
- [ ] Move the protocol section from the appendix to the theoretical background
- [ ] Add citations for the protocol (Diffie-Hellman)
- [x] In the Theoretical background review the IRC protocol and explain why it does not meet demand

**Comment by matanpugach** [comment]
Use as many "well-known concepts" as possible in the protocol. Don't invent the wheel where it is not needed
