### ISSUE TITLE
Filter Match Screen

### ISSUE THREAD

**Issue by saifun** [TechnionYP5779/team1-Social-Geha#22]
Creating a form for matching a new conversation for group 1 or 2

**Comment by ofiralexi** [comment]
![image](https://user-images.githubusercontent.com/37834992/55464415-c3b7bd00-5603-11e9-8a46-0fcb3f80323d.png)

**Comment by ofiralexi** [comment]
Splitted into 3 screens (right now under settings - where to put it ?) @saifun
