### ISSUE TITLE
Previous Chats Screen

### ISSUE THREAD

**Issue by saifun** [TechnionYP5779/team1-Social-Geha#24]

**Comment by ofiralexi** [comment]
![image](https://user-images.githubusercontent.com/37834992/55464526-f82b7900-5603-11e9-9b5c-12c8b7bd1a1b.png)

**Comment by ofiralexi** [comment]
why is the RTL of this layout is different than #23  ?
@saifun  @matanpugach

**Comment by saifun** [comment]
That’s a good question. 
I think we should really turn it over.
