### ISSUE TITLE
Settings Screen

### ISSUE THREAD

**Issue by saifun** [TechnionYP5779/team1-Social-Geha#25]

**Comment by matanpugach** [comment]
![image](https://user-images.githubusercontent.com/27849930/55465032-fdd58e80-5604-11e9-83b1-b0d238f36a44.png)

**Comment by matanpugach** [comment]
add delete my account button - maybe in red with icon ?

**Comment by ofiralexi** [comment]
Can you add an Intent to get from Main activity to this activity? If so, I believe we can close this issue :)
@matanpugach

**Comment by matanpugach** [comment]
@ofiralexi done.
