### ISSUE TITLE
Information Edit Screen

### ISSUE THREAD

**Issue by saifun** [TechnionYP5779/team1-Social-Geha#26]

**Comment by matanpugach** [comment]
![image](https://user-images.githubusercontent.com/27849930/55464937-d1217700-5604-11e9-8552-48e122b2b0c1.png)

**Comment by ofiralexi** [comment]
Can you send a photo once this is done ? So we will review it on phone :)

**Comment by matanpugach** [comment]
Use this screen also after the profile creation
