### ISSUE TITLE
Information Sharing Screen

### ISSUE THREAD

**Issue by saifun** [TechnionYP5779/team1-Social-Geha#27]

**Comment by ofiralexi** [comment]
![image](https://user-images.githubusercontent.com/37834992/55464899-c0710100-5604-11e9-88e5-8bd1ff81be35.png)

**Comment by matanpugach** [comment]
Each line a name, checkbox, and photo

**Comment by matanpugach** [comment]
do it in the same way of the list of 'conversactions\chats' to get a list of persons and present it.
