### ISSUE TITLE
Next Week : To Dos

### ISSUE THREAD

**Issue by ofiralexi** [TechnionYP5779/team1-Social-Geha#35]
some issues needed to be issued in next week meeting :
- [ ] let user upload image (or interface with existing APIs like Facebook ? )
- [ ] take anonymous pictures from src -what about https://github.com/wayou/anonymous-animals like ? need to generate one of our own
- [ ] connect between User class to Person class - to do so we need to figure out where we are taking description and imageUrl from
- [ ] what's this message in login - redundant ?
- [ ] is remember me checkbox redundant because we already use the remember me screen

**Comment by yoavz1997** [comment]
@ofiralexi The pictures belong to Google, so we either have to design our own, or find license free pictures.

**Comment by ofiralexi** [comment]
Yep. edited
