### ISSUE TITLE
High Level Design: Introduction

### ISSUE THREAD

**Issue by ShaiZeevi** [TechnionYP5779/team1-Social-Geha#4]

**Comment by ShaiZeevi** [comment]
Section 1

**Comment by saifun** [comment]
Information could be find in the meeting summary I wrote.

**Comment by ShaiZeevi** [comment]
The HLD document (containing this chapter) is available at the following link:
https://docs.google.com/document/d/15izKhZkrHcyp8mTVWHNzbp4o2QUEUGo3kCcO6lFFh0Y/edit?usp=sharing
