### ISSUE TITLE
Implement anonymous identity generator

### ISSUE THREAD

**Issue by ofiralexi** [TechnionYP5779/team1-Social-Geha#42]
- [x] identity generator using different colors (background tint maybe ? need to be checked)
- [x] #37 add to user List<PersonIDS> that he identifies to and split name into anonymous name and real name

**Comment by matanpugach** [comment]
Please create about 100 possible profile pictures

**Comment by ShaiZeevi** [comment]
Colors are now automatically added to the image, In order to add a hex code to an array
![image](https://user-images.githubusercontent.com/36810747/57282777-6a392700-70b6-11e9-8a99-846040580c52.png)
Now, there are about 11 different colors and 5 photos. I'll add more photos and colors soon
