### ISSUE TITLE
Make sure everything is in Hebrew

### ISSUE THREAD

**Issue by ShaiZeevi** [TechnionYP5779/team1-Social-Geha#46]

**Comment by ofiralexi** [comment]
found string in english - Search (changed to hebrew)
lets try to check it again

**Comment by yoavz1997** [comment]
I used the ".*" regex to find all the strings and could find any in English.
How do manage to find more?

**Comment by ofiralexi** [comment]
![image](https://user-images.githubusercontent.com/37834992/57224728-fdb91c00-7012-11e9-8ca7-9eaf2a27860d.png)
Say it in code

**Comment by yoavz1997** [comment]
What do you mean by "saying stuff in code"?
I used the builtin system to search for strings (using the regex ".*") and could find English strings.
I would love to know if you are using a different technique

**Comment by ofiralexi** [comment]
nope just passed through this java file (I believe it was allChats) and saw "Search"
