### ISSUE TITLE
High Level Design: Theoretical Background and Client Story

### ISSUE THREAD

**Issue by ShaiZeevi** [TechnionYP5779/team1-Social-Geha#5]
Section 2

**Comment by ShaiZeevi** [comment]
This is a great place to incorporate the findings from Or's report which @saifun got for us

**Comment by saifun** [comment]
Can you please assign me? I can’t find how to do it from my phone.

**Comment by ShaiZeevi** [comment]
You got it

**Comment by saifun** [comment]
Uploaded to a doc - https://docs.google.com/document/d/1Q-EyG2PtI4THpjGg97VSz9Dan3_kB8IhB27UGno0QN4/edit?usp=sharing

**Comment by ShaiZeevi** [comment]
The HLD document (containing this chapter) is available at the following link:
https://docs.google.com/document/d/15izKhZkrHcyp8mTVWHNzbp4o2QUEUGo3kCcO6lFFh0Y/edit?usp=sharing
