### ISSUE TITLE
Delete my account 

### ISSUE THREAD

**Issue by matanpugach** [TechnionYP5779/team1-Social-Geha#52]
Make delete your account button fully operational

**Comment by saifun** [comment]
- [ ] Are you sure you want to delete the account?
- [ ] Delete user from DB
- [ ] Erase connection params (exit to code screen)
- [ ] Enable other users to send messages to a deleted user.

**Comment by Itamaror** [comment]
Implemented remove user, user the database and removed local files from user phone

Before in DB:
![קיים](https://user-images.githubusercontent.com/44427296/58492237-2eefbc80-8179-11e9-91c2-77ac251ed5aa.png)

After in DB:
![לא קיים](https://user-images.githubusercontent.com/44427296/58492259-357e3400-8179-11e9-9dd2-9ffd25548ad8.png)

Before on device:
![Screenshot_20190528-184328](https://user-images.githubusercontent.com/44427296/58492377-7118fe00-8179-11e9-8813-d4b3d3d706cd.jpg)

After on device:

![Screenshot_20190528-184452](https://user-images.githubusercontent.com/44427296/58492392-78d8a280-8179-11e9-9bb5-2c7115cd95b9.jpg)
