### ISSUE TITLE
Setting screen Makeover

### ISSUE THREAD

**Issue by matanpugach** [TechnionYP5779/team1-Social-Geha#53]
Re-design settings screen to be what was the main screen with the following enhancements:
- [x] Display the real name

- [x] Display the  anonymous name

- [x] Display the anon photo

- [x] Add a 'contact us' button

**Comment by ofiralexi** [comment]
TODO : need to create function to recieve more then just userID (profile id, anonymous identity)

**Comment by matanpugach** [comment]
@ofiralexi is this another goal for this issue?

**Comment by ofiralexi** [comment]
I can't finish this issue without it . Need to check how to do it
