### ISSUE TITLE
Message timestamp

### ISSUE THREAD

**Issue by matanpugach** [TechnionYP5779/team1-Social-Geha#57]
- [x] In the main chat screen - display when was the last message sent
- [x] When clicking a message in the chat, display it's time.
- [ ] Divide to day in the chat (? was not initially defined in the meeting, just thought about it now)

**Comment by Itamaror** [comment]
@matanpugach " Divide to day in the chat " what did you mean by this?

**Comment by matanpugach** [comment]
nvm @Itamaror , can close
