### ISSUE TITLE
High Level Design: Basic System Functionalities

### ISSUE THREAD

**Issue by ShaiZeevi** [TechnionYP5779/team1-Social-Geha#6]
Section 3

**Comment by saifun** [comment]
Uploaded to a doc - https://docs.google.com/document/d/1Q-EyG2PtI4THpjGg97VSz9Dan3_kB8IhB27UGno0QN4/edit?usp=sharing

**Comment by saifun** [comment]
Uploaded the doc -
https://docs.google.com/document/d/1hi0rlE-QWN76-rzA-5e2K7-I0qe5I5bc3sm7XKU2bNI/edit?usp=sharing

**Comment by ShaiZeevi** [comment]
The HLD document (containing this chapter) is available at the following link:
https://docs.google.com/document/d/15izKhZkrHcyp8mTVWHNzbp4o2QUEUGo3kCcO6lFFh0Y/edit?usp=sharing
