### ISSUE TITLE
Chat main screen doesn't update

### ISSUE THREAD

**Issue by matanpugach** [TechnionYP5779/team1-Social-Geha#63]
The main screen does not update if a new conversation is started, while you're in the main chat screen

**Comment by ShaiZeevi** [comment]
I believe that both this issue and #63 stem from the fact that the AllActivitiesScreen is not re-rendered upon the arrival of a new message, but only once. The screen doesn't update if a new conversation is started (causing this issue) and it doesn't update when a new message arrives (causing #67).

**Comment by ShaiZeevi** [comment]
![image](https://user-images.githubusercontent.com/36810747/57285209-61971f80-70bb-11e9-88e9-e24c38a48c22.png)

It's manifesting itself in new ways
