### ISSUE TITLE
Admin app integration

### ISSUE THREAD

**Issue by matanpugach** [TechnionYP5779/team1-Social-Geha#64]
Admin website that runs the code generation application - frontend and backend
- [x] Update the kind of users to be the kind of their hospitalisation.

Saifun's tasks:
- [x] UI - until friday - Saifun.
- [x] Edit user - add form - Saifun
- [x] Make all the buttons close the form - Saifun
- [x]  Present user data in 'find users' - present the info - Saifun
- [x] Add 'are you sure' qs before deleting a user - Saifun
- [x] Add field correctness checks to the forms - Saifun
- [x] Add error messages, frontend (bad user data) and backend (database issue) - Saifun
- [x] Add a user & generate the code for him - Saifun

Matan's tasks:
- [x] Convert fields from the form to the firebase + userCode - Matan.
- [x] Present user data in 'find users' - Retrieve from DB - Matan
- [x] Delete a user from DB - Matan
- [x] Edit user - save in DB - Matan
- [x] Adding an existing user - error message - Matan
- [x] Add password protection for the whole website - Matan
- [x] Firebase.json writing rules - Matan

**Comment by saifun** [comment]
The UI is finished.
You may start working on the backend (exporting HTML fields into JS, and inserting to the DB).
For now the JS is a bit messy because I left functions we *may* need, but the fields they deal with do not exist anymore. You may delete these functions once you finish.
For now, I created a JS variable named "code" - and initialized it with an empty string. Please use it when adding a user to the DB, as I'll write the code into this var.
We can talk about it more if you wish :) @matanpugach

**Comment by saifun** [comment]
And - we need to think if we want to change the site to HEB, as it written in English for now.
I think I may want to discuss it with the customer.

**Comment by saifun** [comment]
Some pictures of the work:
![image](https://user-images.githubusercontent.com/44426592/58583663-338da100-825d-11e9-9391-94ea5ee277b3.png)
![image](https://user-images.githubusercontent.com/44426592/58583685-3ee0cc80-825d-11e9-8b74-7839152c7eb3.png)

**Comment by saifun** [comment]
Next week tasks for Saifun:

- [ ] Add password protection for the website

- [ ] Upload the website to a real domain

- [ ] Add field correctness checks to the forms 

- [ ] Present user data in 'find users'

- [ ] Add 'are you sure' qs before deleting a user

**Comment by saifun** [comment]
Find a user:
![image](https://user-images.githubusercontent.com/44426592/59093487-bd540300-891c-11e9-986e-df2c66bbfd9b.png)

**Comment by saifun** [comment]
@matanpugach 
I would be happy if you could implement the deletion part, so I can add the frontend UX messages for the user in this form as well.
As for your adding an existing user task - you may just store the result in a boolean var and I'll add it as a user message if you prefer :)

**Comment by matanpugach** [comment]
@saifun done :)

> As for your adding an existing user task - you may just store the result in a boolean var and I'll add it as a user message if you prefer :)
you can insert it in line 136

**Comment by saifun** [comment]
As for the 'are you sure?' part before deleting a user - I thought it would be too crowded to open a new dialog with this question, on top of the existing one.
Do you think that adding a text saying that (that exists all the time) is enough?
@matanpugach

**Comment by matanpugach** [comment]
@saifun your decision

**Comment by saifun** [comment]
I still have some things to check before declaring this issue as completed
