### ISSUE TITLE
Anonymity exposure test-case

### ISSUE THREAD

**Issue by matanpugach** [TechnionYP5779/team1-Social-Geha#65]
When a user goes exposed, update the search in the main screen to search by the real name and not the anonymous name

**Comment by ShaiZeevi** [comment]
related to #48

**Comment by ShaiZeevi** [comment]
Do the current standards of anonymity qualify for this test case? I tried both in a "hard-coded share" and with an actual person on the other side (many thanks to @yoavz1997 for participating).

Here is a picture proving that searches react to the real name:
![image](https://user-images.githubusercontent.com/36810747/58337764-2d5b8700-7e4f-11e9-9515-3a6a908940de.png)
