### ISSUE TITLE
Every message is shown twice

### ISSUE THREAD

**Issue by ShaiZeevi** [TechnionYP5779/team1-Social-Geha#66]
As shown here (I only sent the first two messages):
![image](https://user-images.githubusercontent.com/36810747/57224345-d6ae1a80-7011-11e9-8811-5b019c62f01a.png)

**Comment by ofiralexi** [comment]
@ShaiZeevi is it like it for the other user as well ?

**Comment by ShaiZeevi** [comment]
No, the new user is fine. So should I close this?
![image](https://user-images.githubusercontent.com/36810747/57230053-2693de00-7020-11e9-8d35-7b3dd5986f2d.png)

**Comment by ShaiZeevi** [comment]
Yes, it is. It happens whenever the other side of the conversation hasn't replied yet

**Comment by ShaiZeevi** [comment]
![image](https://user-images.githubusercontent.com/36810747/57230642-7b842400-7021-11e9-891e-315ead1050b9.png)

.vs.

![image](https://user-images.githubusercontent.com/36810747/57230653-8474f580-7021-11e9-9dba-d4ea32b1aff4.png)

**Comment by ShaiZeevi** [comment]
Scratch that, all messages since the last time the app was opened are rendered twice
![image](https://user-images.githubusercontent.com/36810747/57235256-26e5a680-702b-11e9-8d67-be5fdc3c54bc.png)

(He said whilst exposing the identity of one scientific lion, or should I say lioness)

**Comment by ShaiZeevi** [comment]
I think it's back:
![image](https://user-images.githubusercontent.com/36810747/58337974-a529b180-7e4f-11e9-96e6-da03de1fe58c.png)

@Itamaror, do you remember what to source of the problem was?

**Comment by Itamaror** [comment]
It happens due to a race condition between the recive message listener and the initial population of the message list. I am pretty sure it's solved on the sender side, I'll have another look at the code and look for what I missed.

**Comment by ShaiZeevi** [comment]
What's the connection to the list population and the chat? They occur in different screens (AllChats vs the ChatActivity). Also, if there's a race condition, is it possible to just make one wait a little?
