### ISSUE TITLE
Fix Anonymity images 

### ISSUE THREAD

**Issue by matanpugach** [TechnionYP5779/team1-Social-Geha#75]
to focus on the animal face, and not only it's center.

**Comment by ofiralexi** [comment]
Can't it be done simply by croping the original image (for example the donkey one ? ) @ShaiZeevi

**Comment by ShaiZeevi** [comment]
Maybe, but it's also sort of a non-issue since these images have been revoked. So, no one can get them anymore

**Comment by ShaiZeevi** [comment]
@matanpugach 
I'm closing this, we just don't have the bandwidth to deal with someone else's CircleImageView. Plus, the image in question is not available to users anymore
