### ISSUE TITLE
Make user info edit update the current user

### ISSUE THREAD

**Issue by matanpugach** [TechnionYP5779/team1-Social-Geha#84]

**Comment by ShaiZeevi** [comment]
Does this include updating the name for every person with whom you've shared your real name?

**Comment by matanpugach** [comment]
@ShaiZeevi no, this is only making the info screen working.

**Comment by ShaiZeevi** [comment]
Ok, so what is the screen currently capable of doing? Does it just override that specific person's information on the server right (or registers them)?

**Comment by matanpugach** [comment]
If this screen is activated via registering - registers them
If this screen is activated for an existing user - override fields
