### ISSUE TITLE
Fix user data sharing bug 

### ISSUE THREAD

**Issue by saifun** [TechnionYP5779/team1-Social-Geha#97]

**Comment by ShaiZeevi** [comment]
@saifun, do you know what this issue concerns?

**Comment by saifun** [comment]
No. @ofiralexi told me to open it 😯

**Comment by ofiralexi** [comment]
It's the bug in which changing your name after sharing your info with another, doesn't update the name shown to the shared peron.

**Comment by ShaiZeevi** [comment]
fixed in #103 by @yoavz1997 and myself
